### ISSUE TITLE
MultiDimensional visualization

### ISSUE THREAD

**Issue by tsoiadelina** [vktrbr/optimization_ml#35]
# Make visualization 
## for 1-variable functions
- [x] animation plot with the movement of the point

## for 2-variables functions 
- [x] make contour line plot
- [x] add  movement of the point
- [x] add movement of the point on the contour plot

##  for all functions 
- [x] graph of the decreasing gradient norm and the function values for each iteration.

**Comment by vktrbr** [comment]
@tsoiadelina tasks:

- [ ]  add movement of the point on the contour plot
- [x]  graph of the decreasing gradient norm and the function values for each iteration.

**branch:** 35-multidimensional-visualization-CONTOUR-ANIM-+-FLAT-CHARTS

**Comment by tsoiadelina** [comment]
one dimensional were canceled .Animation contour plot can not be solved

**Comment by vktrbr** [comment]
[visualizer.py](https://github.com/vktrbr/optimization_ml/blob/main/MultiDimensionalOptimization/drawing/visualizer.py)
