### ISSUE TITLE
Streamlit App

### ISSUE THREAD

**Issue by vktrbr** [vktrbr/optimization_ml#52]
### Input requirements
- [x] Get an excel or csv file that has X and y in it
- [x] Get a name of column y
- [x] Type of regression
- [x] Degree of polynomial regression
- [x] Optimization algorithm (Calculate using matrices or gradient methods)
- [x] button with regulators type 
- [x] choose x and y columns

### Output requirements 
- [x] Basic regression metrics
- [x] Excel file available for download

**Comment by tsoiadelina** [comment]
am I need none type regulator?

**Comment by vktrbr** [comment]
[streamlit_app.py](https://github.com/vktrbr/optimization_ml/blob/main/Regression/streamlit_app.py)
