### ISSUE TITLE
Parsing

### ISSUE THREAD

**Issue by tsoiadelina** [vktrbr/optimization_ml#54]
#### Make pd.DataFrame from given excel or csv file
 Input data format: a table is given, where the column headers are passed in the first row. Indexes are missing
- [x] Chek file format 
- [x] Make a list with names of columns
- [x] Make a DataFrame

**Comment by tsoiadelina** [comment]
How take path from file(which was uploaded on streamlit)?

**Comment by vktrbr** [comment]
https://github.com/vktrbr/optimization_ml/blob/a193eb7ae1b283ce2f5a253210a9c9d691a99ff3/Regression/streamlit_app.py#L85-L98

https://github.com/vktrbr/optimization_ml/blob/a193eb7ae1b283ce2f5a253210a9c9d691a99ff3/Regression/streamlit_app.py#L143-L155
