### ISSUE TITLE
Notebook refactoring

### ISSUE THREAD

**Issue by vktrbr** [vktrbr/optimization_ml#67]
# Example notebook
## Make user guide by function from
- [x] [algorithms.py](https://github.com/vktrbr/optimization_ml/blob/main/Regression/algorithms.py)
- [x] [visualization.py](https://github.com/vktrbr/optimization_ml/blob/main/Regression/visualization.py)

by refactoring 
[example_notebook.ipynb](https://github.com/vktrbr/optimization_ml/blob/main/Regression/example_notebook.ipynb)

**Comment by tsoiadelina** [comment]
example notebook done:
[example_notebook.ipynb](https://github.com/vktrbr/optimization_ml/blob/main/Regression/example_notebook.ipynb)
