### ISSUE TITLE
Python Packages 

### ISSUE THREAD

**Issue by tsoiadelina** [vktrbr/optimization_ml#71]
## Development of 3 methods
~~Made on GO~~
### Possible inputs 
- [x] Function: Callable
- [x] Limitations of the type of equalities and inequalities: Callable 
- [x] Coordinates of the starting point: Sequence
- [x] Optimization accuracy: Real
### Outputs 
- [x] Coordinates of the extremum point
  Point(TypedDict):
    point: Sequence[Real]
    f_value: Real
- [x] History (TypedDict):
    iteration: List[Integral]
    f_value: List[Real]
    x: List[Sequence]
    message: AnyStr

### Methods
- [x]  Newton’s method under equality constrains

![image](https://user-images.githubusercontent.com/52676181/166677263-e5251a60-d0a4-4d70-998c-d21a976619f3.png)
![image](https://user-images.githubusercontent.com/52676181/166677235-93f35f26-1aa3-444c-97f7-fa112c6ac4ce.png)
![image](https://user-images.githubusercontent.com/52676181/166677178-f13221b9-b09b-4857-9cde-b85373aac669.png)
![image](https://user-images.githubusercontent.com/52676181/166677197-a81fee0a-9b11-4390-bf53-cbd2329b4527.png)

- [x] Log Barrier Method
- [ ] ~~Primal-Dual Interior-Point Methods~~

### Reference
https://www.cs.cmu.edu/~pradeepr/convexopt/Lecture_Slides/primal-dual.pdf (Primal-Dual Interior-Point Methods)
https://www.stat.cmu.edu/~ryantibs/convexopt-S15/scribes/15-barr-method-scribed.pdf ( Log Barrier Method)

![image](https://user-images.githubusercontent.com/52676181/165518079-02b7608e-0837-411e-9a16-c97c286dfffc.png)

![image](https://user-images.githubusercontent.com/52676181/165517886-0c920ad9-0bcc-402a-8fb0-de8d84924c2d.png)

![image](https://user-images.githubusercontent.com/52676181/165517946-eed5e4d8-7b92-4a64-890c-c8cb715e2904.png)

https://www.cs.cmu.edu/~ggordon/10725-F12/scribes/10725_Lecture12.pdf (Newton’s method under equality constrains)

**Comment by vktrbr** [comment]
[algorithms.py](https://github.com/vktrbr/optimization_ml/blob/main/Inner_point/algorithms.py)

**Comment by vktrbr** [comment]
Primal-Dual Interior-Point Methods isn't done
